/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.ctrlCodigo;
import Controlador.ctrlRecuperacion;
import Modelo.User;

/**
 *
 * @author edeni
 */
public class frmCodigo extends javax.swing.JFrame {

    /**
     * Creates new form frmCodigo
     */
    public frmCodigo() {
        initComponents();
    }
    
    public static void initFrmCodigo(){
        User Modelo = new User();
        frmCodigo Vista = new frmCodigo();
        frmRecuperacion vistaRecuperacion = new frmRecuperacion();
        ctrlRecuperacion controladorRecuperacion = new ctrlRecuperacion(Modelo,vistaRecuperacion);
        ctrlCodigo controlador = new ctrlCodigo(Modelo,Vista,controladorRecuperacion);
        
        
        Vista.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVCodigo = new javax.swing.JButton();
        btnvolvercodigo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCode.setBackground(new java.awt.Color(255, 255, 255));
        txtCode.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 161, 349, 56));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Escriba su Codigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        btnVCodigo.setBackground(new java.awt.Color(113, 181, 48));
        btnVCodigo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnVCodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnVCodigo.setText("Verificar");
        jPanel1.add(btnVCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 200, 40));

        btnvolvercodigo.setBackground(new java.awt.Color(113, 181, 48));
        btnvolvercodigo.setForeground(new java.awt.Color(255, 255, 255));
        btnvolvercodigo.setText("<---");
        jPanel1.add(btnvolvercodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 26, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCodigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initFrmCodigo();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnVCodigo;
    public javax.swing.JButton btnvolvercodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCode;
    // End of variables declaration//GEN-END:variables
}
