/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlAjustes;

/**
 *
 * @author jluis
 */
public class jpAjustes extends javax.swing.JPanel {

    /**
     * Creates new form jpAjustes
     */
    public jpAjustes() {
        initComponents();
        jpAjustes Vista = this ;
        frmInicio inicio = new frmInicio();
        ctrlAjustes controlador = new ctrlAjustes(this,inicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnSoporte = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnAcercaDe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnPoliticasDePrivacidad = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Ajustes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 160, 60));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Acerca de la app");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 170, -1));

        btnSoporte.setBackground(new java.awt.Color(255, 255, 255));
        btnSoporte.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnSoporte.setForeground(new java.awt.Color(255, 102, 0));
        btnSoporte.setText(">");
        btnSoporte.setBorder(null);
        add(btnSoporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 100, 50));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 410, 10));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText("Soporte");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 410, 10));

        btnAcercaDe.setBackground(new java.awt.Color(255, 255, 255));
        btnAcercaDe.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnAcercaDe.setForeground(new java.awt.Color(255, 102, 0));
        btnAcercaDe.setText(">");
        btnAcercaDe.setBorder(null);
        add(btnAcercaDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 100, 50));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText("Politicas de privacidad");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        btnPoliticasDePrivacidad.setBackground(new java.awt.Color(255, 255, 255));
        btnPoliticasDePrivacidad.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnPoliticasDePrivacidad.setForeground(new java.awt.Color(255, 102, 0));
        btnPoliticasDePrivacidad.setText(">");
        btnPoliticasDePrivacidad.setBorder(null);
        add(btnPoliticasDePrivacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 100, 50));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 410, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAcercaDe;
    public javax.swing.JButton btnPoliticasDePrivacidad;
    public javax.swing.JButton btnSoporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
