/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlDestinos;
import java.awt.BorderLayout;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author edeni 
 */
public class jpDestinos extends javax.swing.JPanel {

    /**
     * Creates new form jpDestinos
     */
    public jpDestinos() {
        initComponents();
      //aqui debe ir el controlador 
      frmInicio inicio = new frmInicio();
        ctrlDestinos controlador = new ctrlDestinos(this, inicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLugarTuristico = new javax.swing.JButton();
        btnHospedaje = new javax.swing.JButton();
        btnSubidos = new javax.swing.JButton();
        btnPaqueteViaje = new javax.swing.JButton();
        btnRestaurante = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(830, 600));
        setMinimumSize(new java.awt.Dimension(830, 600));
        setPreferredSize(new java.awt.Dimension(830, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 140, 0));
        jLabel2.setText("Añade un destino que haga soñar a tus visitantes.");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 140, 0));
        jLabel3.setText("turistico");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 140, 0));
        jLabel1.setText("¡Es hora de expandir horizontes!");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 140, 0));
        jLabel12.setText("viaje");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 140, 0));
        jLabel5.setText("Lugar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 140, 0));
        jLabel11.setText("Paquetes de");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 140, 0));
        jLabel6.setText("Hospedaje");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 140, 0));
        jLabel8.setText("Restaurante");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 140, 0));
        jLabel10.setText("Subidos");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        btnLugarTuristico.setBackground(new java.awt.Color(251, 212, 95));
        btnLugarTuristico.setBorder(null);
        btnLugarTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugarTuristicoActionPerformed(evt);
            }
        });
        add(btnLugarTuristico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 260, 110));

        btnHospedaje.setBackground(new java.awt.Color(251, 212, 95));
        btnHospedaje.setBorder(null);
        btnHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospedajeActionPerformed(evt);
            }
        });
        add(btnHospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 260, 110));

        btnSubidos.setBackground(new java.awt.Color(251, 212, 95));
        btnSubidos.setBorder(null);
        btnSubidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubidosActionPerformed(evt);
            }
        });
        add(btnSubidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 250, 50));

        btnPaqueteViaje.setBackground(new java.awt.Color(251, 212, 95));
        btnPaqueteViaje.setBorder(null);
        btnPaqueteViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteViajeActionPerformed(evt);
            }
        });
        add(btnPaqueteViaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 310, 260, 110));

        btnRestaurante.setBackground(new java.awt.Color(251, 212, 95));
        btnRestaurante.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnRestaurante.setForeground(new java.awt.Color(255, 140, 0));
        btnRestaurante.setBorder(null);
        btnRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauranteActionPerformed(evt);
            }
        });
        add(btnRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 260, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubidosActionPerformed
       /* jpSubidos pl = new jpSubidos(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.setLayout(new AbsoluteLayout());
       contentD.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); */  
    }//GEN-LAST:event_btnSubidosActionPerformed

    private void btnLugarTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugarTuristicoActionPerformed
        // TODO add your handling code here:
         // Crea una instancia del panel
    /*jpLugarTuristico pl = new jpLugarTuristico(); 
    pl.setSize(830, 600);    // Establece el tamaño  
    pl.setLocation(0, 0);    // Establece la ubicación 
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.setLayout(new AbsoluteLayout());
       contentD.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint();         // Redibuja el contenedor*/
    }//GEN-LAST:event_btnLugarTuristicoActionPerformed

    private void btnHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospedajeActionPerformed
        // TODO add your handling code here:
        
              System.err.println("se dio clic");
       //jpHospedaje pl = new jpHospedaje(); // Crea una instancia 
           panelRojo panel = new panelRojo();
         //  frmInicio PantallaPrincipal = new frmInicio();
       //frmInicio fI = new frmInicio();
        
     //  pl.setSize(830, 600);    // Establece el tamaño  
       //pl.setLocation(0, 0);    // Establece la ubicación 
    //jpDestinos pl = new jpDestinos(); // Crea una instancia 
    //    
      //  pl.setSize(830, 600);    // Establece el tamaño  
        //pl.setLocation(0, 0);    // Establece la ubicación 
      // content.setLayout(new AbsoluteLayout());
       //content.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
        
        /*jpHospedaje pl = new jpHospedaje(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);   // Establece la ubicación
        
       content.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.setLayout(new AbsoluteLayout());
       contentD.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); */
    }//GEN-LAST:event_btnHospedajeActionPerformed

    private void btnRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauranteActionPerformed
        // TODO add your handling code here:
        /*jpRestaurante pl = new jpRestaurante(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.setLayout(new AbsoluteLayout());
       contentD.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); */
    }//GEN-LAST:event_btnRestauranteActionPerformed

    private void btnPaqueteViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteViajeActionPerformed
        // TODO add your handling code here:
        /*jpPaquetes pl = new jpPaquetes(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.setLayout(new AbsoluteLayout());
       contentD.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); */
    }//GEN-LAST:event_btnPaqueteViajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnHospedaje;
    public javax.swing.JButton btnLugarTuristico;
    public javax.swing.JButton btnPaqueteViaje;
    public javax.swing.JButton btnRestaurante;
    public javax.swing.JButton btnSubidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
