/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import java.awt.BorderLayout;

/**
 *
 * @author edeni
 */
public class jpDestinos extends javax.swing.JPanel {

    /**
     * Creates new form jpDestinos
     */
    public jpDestinos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLugarTuristico = new javax.swing.JButton();
        btnHospedaje = new javax.swing.JButton();
        btnSubidos = new javax.swing.JButton();
        btnPaqueteViaje = new javax.swing.JButton();
        btnRestaurante = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(830, 600));
        setMinimumSize(new java.awt.Dimension(830, 600));
        setPreferredSize(new java.awt.Dimension(830, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentD.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 140, 0));
        jLabel1.setText("¡Es hora de expandir horizontes!");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 140, 0));
        jLabel2.setText("Añade un destino que haga soñar a tus visitantes.");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 140, 0));
        jLabel3.setText("turistico");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 140, 0));
        jLabel5.setText("Lugar");

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 140, 0));
        jLabel12.setText("viaje");

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 140, 0));
        jLabel11.setText("Paquetes de");

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 140, 0));
        jLabel6.setText("Hospedaje");

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 140, 0));
        jLabel8.setText("Restaurante");

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 140, 0));
        jLabel10.setText("Subidos");

        btnLugarTuristico.setBackground(new java.awt.Color(251, 212, 95));
        btnLugarTuristico.setBorder(null);
        btnLugarTuristico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLugarTuristicoActionPerformed(evt);
            }
        });

        btnHospedaje.setBackground(new java.awt.Color(251, 212, 95));
        btnHospedaje.setBorder(null);
        btnHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospedajeActionPerformed(evt);
            }
        });

        btnSubidos.setBackground(new java.awt.Color(251, 212, 95));
        btnSubidos.setBorder(null);
        btnSubidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubidosActionPerformed(evt);
            }
        });

        btnPaqueteViaje.setBackground(new java.awt.Color(251, 212, 95));
        btnPaqueteViaje.setBorder(null);
        btnPaqueteViaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaqueteViajeActionPerformed(evt);
            }
        });

        btnRestaurante.setBackground(new java.awt.Color(251, 212, 95));
        btnRestaurante.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        btnRestaurante.setForeground(new java.awt.Color(255, 140, 0));
        btnRestaurante.setBorder(null);
        btnRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestauranteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentDLayout = new javax.swing.GroupLayout(contentD);
        contentD.setLayout(contentDLayout);
        contentDLayout.setHorizontalGroup(
            contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentDLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1))
            .addGroup(contentDLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2))
            .addGroup(contentDLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLugarTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))))
                .addGap(70, 70, 70)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel6))
                    .addComponent(btnHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(contentDLayout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8)))
                .addGap(70, 70, 70)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPaqueteViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)))))
            .addGroup(contentDLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubidos, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))))
        );
        contentDLayout.setVerticalGroup(
            contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentDLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(51, 51, 51)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel3))
                    .addComponent(btnLugarTuristico, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel5))
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6))
                    .addComponent(btnHospedaje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel8))
                    .addComponent(btnPaqueteViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11))
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel12)))
                .addGap(80, 80, 80)
                .addGroup(contentDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSubidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentDLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10))))
        );

        add(contentD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubidosActionPerformed
        jpSubidos pl = new jpSubidos(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.add(pl, BorderLayout.CENTER); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); 
    }//GEN-LAST:event_btnSubidosActionPerformed

    private void btnLugarTuristicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLugarTuristicoActionPerformed
        // TODO add your handling code here:
        jpLugarTuristico pl = new jpLugarTuristico(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.add(pl, BorderLayout.CENTER); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); 
    }//GEN-LAST:event_btnLugarTuristicoActionPerformed

    private void btnHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospedajeActionPerformed
        // TODO add your handling code here:
        jpHospedaje pl = new jpHospedaje(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.add(pl, BorderLayout.CENTER); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); 
    }//GEN-LAST:event_btnHospedajeActionPerformed

    private void btnRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestauranteActionPerformed
        // TODO add your handling code here:
        jpRestaurante pl = new jpRestaurante(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.add(pl, BorderLayout.CENTER); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); 
    }//GEN-LAST:event_btnRestauranteActionPerformed

    private void btnPaqueteViajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaqueteViajeActionPerformed
        // TODO add your handling code here:
        jpPaquetes pl = new jpPaquetes(); // Crea una instancia 
        pl.setSize(830, 600);    // Establece el tamaño  
        pl.setLocation(0, 0);    // Establece la ubicación 
    
       contentD.removeAll();      // Elimina todos los componentes del contenedor 'content'
       contentD.add(pl, BorderLayout.CENTER); // Agrega el nuevo panel al centro del contenedor
       contentD.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
       contentD.repaint(); 
    }//GEN-LAST:event_btnPaqueteViajeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnHospedaje;
    public javax.swing.JButton btnLugarTuristico;
    public javax.swing.JButton btnPaqueteViaje;
    public javax.swing.JButton btnRestaurante;
    public javax.swing.JButton btnSubidos;
    public javax.swing.JPanel contentD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
