/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlHospedaje;
import Modelo.Hospedaje;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.Base64;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.apache.hc.client5.http.classic.methods.HttpPost;
import org.apache.hc.client5.http.impl.classic.CloseableHttpClient;
import org.apache.hc.client5.http.impl.classic.CloseableHttpResponse;
import org.apache.hc.client5.http.impl.classic.HttpClients;
import org.apache.hc.core5.http.ParseException;
import org.apache.hc.core5.http.io.entity.EntityUtils;
import org.apache.hc.core5.http.io.entity.StringEntity;
import org.json.JSONObject;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author edeni
 */
public class jpHospedaje extends javax.swing.JPanel {

    /**
     * Creates new form jpHospedaje
     */
    public jpHospedaje() {
        
        initComponents();
        Hospedaje Modelo = new Hospedaje();
        jpHospedaje Vista = this ;
        frmInicio inicio = new frmInicio();
        ctrlHospedaje controlador = new ctrlHospedaje(this,Modelo,inicio);
    }
    /*
      public static void initJPHospedaje(){
        Hospedaje Modelo = new Hospedaje();
        jpHospedaje Vista = new jpHospedaje();
        ctrlHospedaje controlador = new ctrlHospedaje(Vista,Modelo);
       // Vista.contentH.add(Vista);
       // Vista.setVisible(true);
    }*/
      /*
      public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               initJPHospedaje();
            }
        });
      
    }*/
    
 

    
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSubidosH = new javax.swing.JButton();
        txtNombreHospedaje = new javax.swing.JTextField();
        txtDescripcionHospedaje = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioHospedaje = new javax.swing.JTextField();
        btnCancelarH = new javax.swing.JButton();
        btnGuardarH = new javax.swing.JButton();
        lbImagenHospedaje = new javax.swing.JLabel();
        btnSubirImagenH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubidosH.setBackground(new java.awt.Color(251, 212, 95));
        btnSubidosH.setForeground(new java.awt.Color(255, 140, 0));
        btnSubidosH.setText("Subidos");
        btnSubidosH.setBorder(null);
        btnSubidosH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubidosHActionPerformed(evt);
            }
        });
        add(btnSubidosH, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 556, 150, 30));

        txtNombreHospedaje.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 1, true));
        txtNombreHospedaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHospedajeActionPerformed(evt);
            }
        });
        add(txtNombreHospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 290, 50));

        txtDescripcionHospedaje.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 1, true));
        add(txtDescripcionHospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 290, 190));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 140, 0));
        jLabel2.setText("Nombre");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 140, 0));
        jLabel3.setText("Precio");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        txtPrecioHospedaje.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 1, true));
        add(txtPrecioHospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 290, 50));

        btnCancelarH.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelarH.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarH.setText("Cancelar");
        add(btnCancelarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 530, 100, 40));

        btnGuardarH.setBackground(new java.awt.Color(51, 153, 0));
        btnGuardarH.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarH.setText("Guardar");
        add(btnGuardarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 530, 100, 40));

        lbImagenHospedaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Subir.png"))); // NOI18N
        add(lbImagenHospedaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, -1, -1));

        btnSubirImagenH.setBackground(new java.awt.Color(255, 140, 0));
        btnSubirImagenH.setForeground(new java.awt.Color(255, 255, 255));
        btnSubirImagenH.setText("Subir Imagen");
        btnSubirImagenH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirImagenHActionPerformed(evt);
            }
        });
        add(btnSubirImagenH, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 130, 40));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 140, 0));
        jLabel1.setText("Subir Hospedajes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubidosHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubidosHActionPerformed
        
    }//GEN-LAST:event_btnSubidosHActionPerformed

    private void txtNombreHospedajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHospedajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHospedajeActionPerformed

    private void btnSubirImagenHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirImagenHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubirImagenHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarH;
    public javax.swing.JButton btnGuardarH;
    public javax.swing.JButton btnSubidosH;
    public javax.swing.JButton btnSubirImagenH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JLabel lbImagenHospedaje;
    public javax.swing.JTextField txtDescripcionHospedaje;
    public javax.swing.JTextField txtNombreHospedaje;
    public javax.swing.JTextField txtPrecioHospedaje;
    // End of variables declaration//GEN-END:variables
}
