/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author edeni
 */
public class jpPaquetes extends javax.swing.JPanel {

    /**
     * Creates new form jpPaquetes
     */
    public jpPaquetes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPT = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSubidosPT = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentPT.setBackground(new java.awt.Color(255, 255, 255));
        contentPT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Paquetes Turisticos");
        contentPT.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 281, -1, -1));

        btnSubidosPT.setBackground(new java.awt.Color(251, 212, 95));
        btnSubidosPT.setForeground(new java.awt.Color(255, 140, 0));
        btnSubidosPT.setText("Subidos");
        btnSubidosPT.setBorder(null);
        btnSubidosPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubidosPTActionPerformed(evt);
            }
        });
        contentPT.add(btnSubidosPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 542, 156, 36));

        add(contentPT, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubidosPTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubidosPTActionPerformed
        jpSubidos pl = new jpSubidos(); // Crea una instancia
        pl.setSize(830, 600);    // Establece el tamaño
        pl.setLocation(0, 0);    // Establece la ubicación

        contentPT.removeAll();      // Elimina todos los componentes del contenedor 'content'
        contentPT.setLayout(new AbsoluteLayout());
        contentPT.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
        contentPT.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
        contentPT.repaint();
    }//GEN-LAST:event_btnSubidosPTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSubidosPT;
    public javax.swing.JPanel contentPT;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
