/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlRestaurante;
import Modelo.Restaurante;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author edeni
 */
public class jpRestaurante extends javax.swing.JPanel {

    /**
     * Creates new form jpRestaurante
     */
    public jpRestaurante() {
        initComponents();
        Restaurante Modelo = new Restaurante();
        jpRestaurante Vista = this ;
        frmInicio inicio = new frmInicio();
        ctrlRestaurante controlador = new ctrlRestaurante(this,Modelo,inicio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentR = new javax.swing.JPanel();
        btnSubidosR = new javax.swing.JButton();
        txtNombreLugarT = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDetallesLugarT = new javax.swing.JTextField();
        lbFotoMenu = new javax.swing.JLabel();
        jbtnGuardar = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();
        lbFotoRestaurante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contentR.setBackground(new java.awt.Color(255, 255, 255));
        contentR.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubidosR.setBackground(new java.awt.Color(251, 212, 95));
        btnSubidosR.setForeground(new java.awt.Color(255, 140, 0));
        btnSubidosR.setText("Subidos");
        btnSubidosR.setBorder(null);
        btnSubidosR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubidosRActionPerformed(evt);
            }
        });
        contentR.add(btnSubidosR, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 156, 36));

        txtNombreLugarT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 1, true));
        txtNombreLugarT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreLugarTActionPerformed(evt);
            }
        });
        contentR.add(txtNombreLugarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 590, 40));

        jLabel2.setForeground(new java.awt.Color(255, 140, 0));
        jLabel2.setText("Fotos Restaurante");
        contentR.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 140, 0));
        jLabel6.setText("Fotos Menu");
        contentR.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 140, 0));
        jLabel3.setText("Nombre");
        contentR.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 140, 0));
        jLabel4.setText("Detalles Restaurante");
        contentR.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        txtDetallesLugarT.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 1, true));
        contentR.add(txtDetallesLugarT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 590, 100));

        lbFotoMenu.setForeground(new java.awt.Color(255, 140, 0));
        lbFotoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Subir.png"))); // NOI18N
        contentR.add(lbFotoMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        jbtnGuardar.setText("Guardar");
        jbtnGuardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contentR.add(jbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 530, 200, 30));

        jbtnCancelar.setText("Cancelar");
        contentR.add(jbtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 530, 200, 30));

        lbFotoRestaurante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Subir.png"))); // NOI18N
        contentR.add(lbFotoRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 320, 140, -1));

        add(contentR, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 600));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubidosRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubidosRActionPerformed
        jpSubidos pl = new jpSubidos(); // Crea una instancia
        pl.setSize(830, 600);    // Establece el tamaño
        pl.setLocation(0, 0);    // Establece la ubicación

        contentR.removeAll();      // Elimina todos los componentes del contenedor 'content'
        contentR.setLayout(new AbsoluteLayout());
        contentR.add(pl, new AbsoluteConstraints(0, 0, 830, 600)); // Agrega el nuevo panel al centro del contenedor
        contentR.revalidate();      // Vuelve a validar el contenedor para que se ajuste a los cambios
        contentR.repaint();
    }//GEN-LAST:event_btnSubidosRActionPerformed

    private void txtNombreLugarTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreLugarTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreLugarTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSubidosR;
    public javax.swing.JPanel contentR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JButton jbtnCancelar;
    public javax.swing.JButton jbtnGuardar;
    public javax.swing.JLabel lbFotoMenu;
    public javax.swing.JLabel lbFotoRestaurante;
    public javax.swing.JTextField txtDetallesLugarT;
    public javax.swing.JTextField txtNombreLugarT;
    // End of variables declaration//GEN-END:variables
}
