/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Controlador.ctrlSubidos;
import Modelo.Subidos;

/**
 *
 * @author edeni
 */

import Tipografias.Fuentes;

public class jpSubidos extends javax.swing.JPanel {

    /**
     * Creates new form jpSubidos
     */
    Fuentes tipoFuente;
    public jpSubidos() {
        initComponents();
        Subidos Modelo = new Subidos();
        jpSubidos Vista = this ;
        ctrlSubidos controlador = new ctrlSubidos(this,Modelo);
        
        
        //Poner tipografia
        tipoFuente = new Fuentes();
        jTituloD.setFont(tipoFuente.fuente(tipoFuente.Baloo,0,30));
        jSubtituloD.setFont(tipoFuente.fuente(tipoFuente.BBhaina,0,14));
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTituloD = new javax.swing.JLabel();
        jSubtituloD = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTituloD.setForeground(new java.awt.Color(255, 140, 0));
        jTituloD.setText("Mis Destinos");
        add(jTituloD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 30));

        jSubtituloD.setForeground(new java.awt.Color(255, 140, 0));
        jSubtituloD.setText("Gestiona, ajusta y asegúrate de que cada uno inspire a tus viajeros.");
        add(jSubtituloD, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 40));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel jSubtituloD;
    public javax.swing.JLabel jTituloD;
    // End of variables declaration//GEN-END:variables
}
